/* automatically generated from settings-dialog.ui */
#ifdef __SUNPRO_C
#pragma align 4 (settings_dialog_ui)
#endif
#ifdef __GNUC__
static const char settings_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char settings_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\"?><interface><object class=\"GtkDialog\" id=\"sett"
  "ings-dialog\"><property name=\"border_width\">5</property><property nam"
  "e=\"title\" translatable=\"yes\">Settings for Task Manager</property><p"
  "roperty name=\"resizable\">False</property><property name=\"modal\">Tru"
  "e</property><property name=\"destroy_with_parent\">True</property><prop"
  "erty name=\"icon_name\">gtk-preferences</property><property name=\"type"
  "_hint\">normal</property><property name=\"has_separator\">False</proper"
  "ty><child internal-child=\"vbox\"><object class=\"GtkVBox\" id=\"dialog"
  "-vbox\"><property name=\"visible\">True</property><property name=\"orie"
  "ntation\">vertical</property><property name=\"spacing\">2</property><ch"
  "ild><object class=\"GtkNotebook\" id=\"notebook\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"show_tabs\">False</property><child><object class=\"GtkHBox\""
  " id=\"hbox\"><property name=\"visible\">True</property><property name=\""
  "border_width\">6</property><child><object class=\"GtkVBox\" id=\"vbox1\""
  "><property name=\"visible\">True</property><property name=\"orientation"
  "\">vertical</property><property name=\"spacing\">6</property><child><ob"
  "ject class=\"GtkFrame\" id=\"frame-interface\"><property name=\"visible"
  "\">True</property><property name=\"label_xalign\">0</property><property"
  " name=\"shadow_type\">none</property><child><object class=\"GtkAlignmen"
  "t\" id=\"alignment-interface\"><property name=\"visible\">True</propert"
  "y><property name=\"top_padding\">6</property><property name=\"left_padd"
  "ing\">12</property><child><object class=\"GtkVBox\" id=\"vbox-interface"
  "\"><property name=\"visible\">True</property><property name=\"orientati"
  "on\">vertical</property><property name=\"spacing\">6</property><child><"
  "object class=\"GtkCheckButton\" id=\"button-show-application-icons\"><p"
  "roperty name=\"label\" translatable=\"yes\">Show application icons</pro"
  "perty><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">False</propert"
  "y><property name=\"draw_indicator\">True</property></object><packing><p"
  "roperty name=\"position\">0</property></packing></child><child><object "
  "class=\"GtkCheckButton\" id=\"button-full-command-line\"><property name"
  "=\"label\" translatable=\"yes\">Show full command lines</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">False</property><property"
  " name=\"draw_indicator\">True</property></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">1</property></packing></child><child><object "
  "class=\"GtkCheckButton\" id=\"button-more-precision\"><property name=\""
  "label\" translatable=\"yes\">Show values with more precision</property>"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">False</property><pro"
  "perty name=\"draw_indicator\">True</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"position\">2</property></packing></child><child><ob"
  "ject class=\"GtkCheckButton\" id=\"button-process-tree\"><property name"
  "=\"label\" translatable=\"yes\">Show processes as tree</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">False</property><property "
  "name=\"draw_indicator\">True</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">False</property><pr"
  "operty name=\"position\">4</property></packing></child><child><object c"
  "lass=\"GtkCheckButton\" id=\"button-show-memory-in-xbytes\"><property n"
  "ame=\"label\" translatable=\"yes\">Show memory usage in bytes</property"
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">False</property><pr"
  "operty name=\"draw_indicator\">True</property></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">False</prope"
  "rty><property name=\"position\">5</property></packing></child><child><o"
  "bject class=\"GtkHBox\" id=\"hbox-toolbar-style\"><property name=\"visi"
  "ble\">True</property><property name=\"spacing\">6</property><child><obj"
  "ect class=\"GtkLabel\" id=\"label-toolbar-style\"><property name=\"visi"
  "ble\">True</property><property name=\"label\" translatable=\"yes\">Tool"
  "bar style:</property></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">False</property><property name=\"posi"
  "tion\">0</property></packing></child><child><placeholder/></child></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">6</property></packin"
  "g></child></object></child></object></child><child type=\"label\"><obje"
  "ct class=\"GtkLabel\" id=\"label-interface\"><property name=\"visible\""
  ">True</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;"
  "Interface style&lt;/b&gt;</property><property name=\"use_markup\">True<"
  "/property></object></child></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">False</property><property name="
  "\"position\">0</property></packing></child><child><object class=\"GtkFr"
  "ame\" id=\"frame-misc\"><property name=\"visible\">True</property><prop"
  "erty name=\"label_xalign\">0</property><property name=\"shadow_type\">n"
  "one</property><child><object class=\"GtkAlignment\" id=\"alignment-misc"
  "\"><property name=\"visible\">True</property><property name=\"top_paddi"
  "ng\">6</property><property name=\"left_padding\">12</property><child><o"
  "bject class=\"GtkVBox\" id=\"vbox-misc\"><property name=\"visible\">Tru"
  "e</property><property name=\"orientation\">vertical</property><property"
  " name=\"spacing\">6</property><child><object class=\"GtkCheckButton\" i"
  "d=\"button-prompt-terminate-task\"><property name=\"label\" translatabl"
  "e=\"yes\">Prompt for terminating tasks</property><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">True</property><proper"
  "ty name=\"receives_default\">False</property><property name=\"draw_indi"
  "cator\">True</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">False</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkCheckB"
  "utton\" id=\"button-show-status-icon\"><property name=\"label\" transla"
  "table=\"yes\">Hide into the notification area</property><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"receives_default\">False</property><property name=\"dr"
  "aw_indicator\">True</property></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">False</property><property na"
  "me=\"position\">1</property></packing></child></object></child></object"
  "></child><child type=\"label\"><object class=\"GtkLabel\" id=\"label-mi"
  "sc\"><property name=\"visible\">True</property><property name=\"label\""
  " translatable=\"yes\">&lt;b&gt;Miscellaneous&lt;/b&gt;</property><prope"
  "rty name=\"use_markup\">True</property></object></child></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Fa"
  "lse</property><property name=\"position\">1</property></packing></child"
  "></object><packing><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkVSeparator\" id=\"vseparator1\"><proper"
  "ty name=\"orientation\">vertical</property></object><packing><property "
  "name=\"expand\">False</property><property name=\"padding\">6</property>"
  "<property name=\"position\">1</property></packing></child><child><objec"
  "t class=\"GtkVBox\" id=\"vbox2\"><property name=\"orientation\">vertica"
  "l</property><property name=\"spacing\">6</property><child><object class"
  "=\"GtkFrame\" id=\"frame-information\"><property name=\"visible\">True<"
  "/property><property name=\"sensitive\">False</property><property name=\""
  "label_xalign\">0</property><property name=\"shadow_type\">none</propert"
  "y><child><object class=\"GtkAlignment\" id=\"alignment-information\"><p"
  "roperty name=\"visible\">True</property><property name=\"top_padding\">"
  "6</property><property name=\"left_padding\">12</property><child><object"
  " class=\"GtkVBox\" id=\"vbox-information\"><property name=\"visible\">T"
  "rue</property><property name=\"orientation\">vertical</property><proper"
  "ty name=\"spacing\">6</property><child><object class=\"GtkHBox\" id=\"h"
  "box-refresh-rate\"><property name=\"visible\">True</property><property "
  "name=\"spacing\">6</property><child><object class=\"GtkLabel\" id=\"lab"
  "el-refresh-rate\"><property name=\"visible\">True</property><property n"
  "ame=\"label\" translatable=\"yes\">Refresh rate:</property></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">0</property></packing></ch"
  "ild><child><object class=\"GtkComboBox\" id=\"combobox-refresh-rate\"><"
  "property name=\"visible\">True</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">1</property></packing></child></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">F"
  "alse</property><property name=\"position\">0</property></packing></chil"
  "d><child><object class=\"GtkLabel\" id=\"label-columns\"><property name"
  "=\"visible\">True</property><property name=\"xalign\">0</property><prop"
  "erty name=\"label\" translatable=\"yes\">Columns:</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">1</property></packing></ch"
  "ild><child><object class=\"GtkAlignment\" id=\"alignment-columns\"><pro"
  "perty name=\"visible\">True</property><property name=\"left_padding\">1"
  "2</property><child><object class=\"GtkScrolledWindow\" id=\"scrolledwin"
  "dow-columns\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"hscrollbar_policy\">never"
  "</property><property name=\"vscrollbar_policy\">never</property><proper"
  "ty name=\"shadow_type\">in</property><child><object class=\"GtkTreeView"
  "\" id=\"treeview-columns\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property></object></child></object></c"
  "hild></object><packing><property name=\"position\">2</property></packin"
  "g></child></object></child></object></child><child type=\"label\"><obje"
  "ct class=\"GtkLabel\" id=\"label-information\"><property name=\"visible"
  "\">True</property><property name=\"label\" translatable=\"yes\">&lt;b&g"
  "t;Information&lt;/b&gt;</property><property name=\"use_markup\">True</p"
  "roperty></object></child></object><packing><property name=\"position\">"
  "0</property></packing></child></object><packing><property name=\"positi"
  "on\">2</property></packing></child></object></child><child type=\"tab\""
  "><object class=\"GtkLabel\" id=\"label\"><property name=\"visible\">Tru"
  "e</property><property name=\"label\" translatable=\"yes\">Settings</pro"
  "perty></object><packing><property name=\"tab_fill\">False</property></p"
  "acking></child><child><placeholder/></child><child type=\"tab\"><placeh"
  "older/></child><child><placeholder/></child><child type=\"tab\"><placeh"
  "older/></child></object><packing><property name=\"position\">1</propert"
  "y></packing></child><child internal-child=\"action_area\"><object class"
  "=\"GtkButtonBox\" id=\"dialog-action_area\"><property name=\"visible\">"
  "True</property><property name=\"layout_style\">end</property><child><ob"
  "ject class=\"GtkButton\" id=\"button-close\"><property name=\"label\">g"
  "tk-close</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">T"
  "rue</property><property name=\"use_stock\">True</property></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "False</property><property name=\"position\">0</property></packing></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"pack_type\">end</property><property name=\"position\">0</prope"
  "rty></packing></child></object></child><action-widgets><action-widget r"
  "esponse=\"0\">button-close</action-widget></action-widgets></object></i"
  "nterface>"
};

static const unsigned settings_dialog_ui_length = 11660u;

